"""Tests for the technical-strategy deterministic depth-enrichment layer.

Covers:
  1. Arabic cybersecurity strategy with one-row pillars is enriched to
     ≥ 3 rows per pillar by enforce_technical_strategy_depth().
  2. Gap guides generated by synthesize_gaps_depth() are not identical
     repeated templates (uniqueness check).
  3. Roadmap synthesized by synthesize_roadmap_depth() contains at least
     4 rows and all mandatory columns.
  4. KPI table contains ≥ 6 metrics after enforce_technical_strategy_depth()
     (consulting mode).
  5. Risk table contains owner/treatment after synthesize_confidence_depth().
  6. Preview/PDF content still contains no trace comments.
  7. python -m py_compile app.py passes.
  8. Existing trace-table safety tests are not broken (re-imported here).

Run:  python -m pytest tests/test_technical_strategy_depth.py -v
  or: python tests/test_technical_strategy_depth.py
"""

import sys
import os
import re
import unittest

# ---------------------------------------------------------------------------
# Set minimal environment variables so app.py can be imported without a
# live database or API keys (init_db requires ADMIN_PASSWORD).
# ---------------------------------------------------------------------------
os.environ.setdefault('ADMIN_PASSWORD', 'test-admin-password')
os.environ.setdefault('SECRET_KEY', 'test-secret-key')
os.environ.setdefault('DATABASE_URL', 'sqlite:///tmp/test_depth.db')
os.environ.setdefault('OPENAI_API_KEY', 'dummy')
os.environ.setdefault('ANTHROPIC_API_KEY', 'dummy')
os.environ.setdefault('GOOGLE_API_KEY', 'dummy')

# ---------------------------------------------------------------------------
# Try to import from real app.py; fall back to stubs if unavailable.
# ---------------------------------------------------------------------------
_USING_REAL_APP = False
_APP = None
try:
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        'app', os.path.join(os.path.dirname(__file__), '..', 'app.py')
    )
    _APP = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(_APP)
    _USING_REAL_APP = True
except Exception as _load_err:
    pass  # tests that need the real app will be skipped


def _skip_if_no_app(fn):
    """Decorator: skip test if app.py could not be imported."""
    import functools

    @functools.wraps(fn)
    def wrapper(self, *args, **kwargs):
        if not _USING_REAL_APP:
            self.skipTest('app.py not importable in this environment')
        return fn(self, *args, **kwargs)
    return wrapper


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_TRACE_COMMENT_RE = re.compile(r'<!--\s*trace:[^>]*?-->', re.IGNORECASE)


def _has_trace_comments(text):
    return bool(_TRACE_COMMENT_RE.search(text or ''))


def _count_initiative_rows(pillar_body):
    """Count pipe-table data rows in a pillar body (not header/separator)."""
    if not pillar_body:
        return 0
    count = 0
    for ln in pillar_body.splitlines():
        s = ln.strip()
        if not (s.startswith('|') and s.endswith('|')):
            continue
        if re.match(r'^\|[\s\-:|]+\|$', s):
            continue
        cells = [c.strip() for c in s.split('|')[1:-1]]
        if cells and cells[0].replace('.', '').isdigit():
            count += 1
    return count


def _parse_pillars(pillars_text):
    """Return list of (title, body) for each ### pillar heading."""
    if not pillars_text:
        return []
    hdr_re = re.compile(
        r'^###\s+(?:Pillar\s*\d*|Strategic\s+Pillar\s*\d*|'
        r'الركيزة(?:\s+الاستراتيجية)?\s*\d*)[^\n]*',
        re.MULTILINE | re.IGNORECASE,
    )
    matches = list(hdr_re.finditer(pillars_text))
    if not matches:
        matches = list(re.finditer(r'^###\s+[^\n]+$', pillars_text, re.MULTILINE))
    out = []
    for i, m in enumerate(matches):
        title = re.sub(r'^###\s+', '', pillars_text[m.start():m.end()]).strip()
        body_end = (matches[i + 1].start() if i + 1 < len(matches)
                    else len(pillars_text))
        body = pillars_text[m.end():body_end]
        out.append((title, body))
    return out


# ---------------------------------------------------------------------------
# Test 7: py_compile
# ---------------------------------------------------------------------------

class TestPyCompile(unittest.TestCase):
    """7. python -m py_compile app.py must pass."""

    def test_app_py_compiles(self):
        import py_compile
        app_path = os.path.join(os.path.dirname(__file__), '..', 'app.py')
        try:
            py_compile.compile(app_path, doraise=True)
        except py_compile.PyCompileError as exc:
            self.fail(f'app.py has a syntax error: {exc}')


# ---------------------------------------------------------------------------
# Test 1: Pillar initiative depth enrichment
# ---------------------------------------------------------------------------

class TestPillarInitiativeDepth(unittest.TestCase):
    """1. One-row pillars are enriched to ≥ 3 rows per pillar."""

    def _make_thin_sections(self):
        """Return a sections dict with 3 pillars each having only 1 initiative."""
        pillars = (
            '## 2. الركائز الاستراتيجية\n\n'
            '### الركيزة الأولى: الحوكمة\n\n'
            'ركيزة الحوكمة والامتثال.\n\n'
            '| # | المبادرة | الوصف | المخرج المتوقع |\n'
            '|---|---------|-------|----------------|\n'
            '| 1 | تأسيس لجنة الحوكمة | تشكيل اللجنة | ميثاق اللجنة |\n\n'
            '### الركيزة الثانية: الحماية التقنية\n\n'
            'ركيزة الحماية التقنية.\n\n'
            '| # | المبادرة | الوصف | المخرج المتوقع |\n'
            '|---|---------|-------|----------------|\n'
            '| 1 | نشر EDR/XDR | تطبيق الحماية | سجل الأجهزة |\n\n'
            '### الركيزة الثالثة: الكشف والاستجابة\n\n'
            'ركيزة الكشف والاستجابة.\n\n'
            '| # | المبادرة | الوصف | المخرج المتوقع |\n'
            '|---|---------|-------|----------------|\n'
            '| 1 | تفعيل SIEM | ربط مصادر السجلات | كتالوج SIEM |\n\n'
        )
        return {
            'vision': '',
            'pillars': pillars,
            'environment': '',
            'gaps': '',
            'roadmap': '',
            'kpis': '',
            'confidence': '',
        }

    @_skip_if_no_app
    def test_one_row_pillars_enriched_to_three(self):
        sections = self._make_thin_sections()
        _APP.enforce_technical_strategy_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
            sector='Government', org_name='Test Org',
        )
        pillars = _parse_pillars(sections['pillars'])
        self.assertGreaterEqual(
            len(pillars), 3,
            f'Expected ≥3 pillars, found {len(pillars)}',
        )
        for title, body in pillars:
            n = _count_initiative_rows(body)
            self.assertGreaterEqual(
                n, 3,
                f'Pillar "{title}" has only {n} initiative row(s); expected ≥3',
            )

    @_skip_if_no_app
    def test_synthesized_pillars_have_three_initiatives(self):
        """synthesize_pillars_depth() on thin input must build 3-init pillars."""
        sections = {'pillars': ''}
        _APP.synthesize_pillars_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
            sector='Government', org_name='Test Org',
        )
        pillars = _parse_pillars(sections.get('pillars', ''))
        self.assertGreaterEqual(len(pillars), 3,
                                'Expected ≥3 pillars from synthesizer')
        for title, body in pillars:
            n = _count_initiative_rows(body)
            self.assertGreaterEqual(
                n, 3,
                f'Synthesized pillar "{title}" has {n} initiative(s); expected ≥3',
            )

    @_skip_if_no_app
    def test_english_synthesized_pillars_have_three_initiatives(self):
        sections = {'pillars': ''}
        _APP.synthesize_pillars_depth(
            sections, lang='en',
            domain='Cyber Security', fw_short='NCA ECC',
            sector='Government', org_name='Test Org',
        )
        pillars = _parse_pillars(sections.get('pillars', ''))
        self.assertGreaterEqual(len(pillars), 3)
        for title, body in pillars:
            n = _count_initiative_rows(body)
            self.assertGreaterEqual(
                n, 3,
                f'EN pillar "{title}" has {n} initiative(s); expected ≥3',
            )

    @_skip_if_no_app
    def test_already_rich_pillars_untouched(self):
        """Pillars with ≥3 initiatives already must not gain spurious rows."""
        sections = self._make_thin_sections()
        # Pre-enrich to 3 rows manually
        sections['pillars'] = sections['pillars'].replace(
            '| 1 | تأسيس لجنة الحوكمة | تشكيل اللجنة | ميثاق اللجنة |',
            '| 1 | تأسيس لجنة الحوكمة | تشكيل اللجنة | ميثاق اللجنة |\n'
            '| 2 | سياسات وإجراءات | إعداد السياسات | حزمة السياسات |\n'
            '| 3 | سجل الضوابط | توثيق الضوابط | سجل الامتثال |',
        )
        parsed_before = _parse_pillars(sections['pillars'])
        self.assertGreater(len(parsed_before), 0,
                           'Expected at least one pillar in test data')
        before = _count_initiative_rows(parsed_before[0][1])
        _APP.enforce_technical_strategy_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
        )
        parsed_after = _parse_pillars(sections['pillars'])
        self.assertGreater(len(parsed_after), 0,
                           'Expected at least one pillar after enrichment')
        after = _count_initiative_rows(parsed_after[0][1])
        self.assertEqual(before, after,
                         f'Already-rich pillar should not change: {before} → {after}')


# ---------------------------------------------------------------------------
# Test 2: Gap guides uniqueness
# ---------------------------------------------------------------------------

class TestGapGuideUniqueness(unittest.TestCase):
    """2. Gap guides must not be identical repeated templates."""

    @_skip_if_no_app
    def test_different_gap_types_produce_different_guides(self):
        sections_governance = {'gaps': (
            '## 4. تحليل الفجوات\n\n'
            '| # | الفجوة | الوصف | الأولوية | الحالة |\n'
            '|---|-------|-------|---------|--------|\n'
            '| 1 | فجوة الحوكمة | غياب لجنة الحوكمة الرسمية | حرجة | مفتوحة |\n'
        )}
        sections_iam = {'gaps': (
            '## 4. تحليل الفجوات\n\n'
            '| # | الفجوة | الوصف | الأولوية | الحالة |\n'
            '|---|-------|-------|---------|--------|\n'
            '| 1 | فجوة إدارة الهوية | غياب PAM وMFA | حرجة | مفتوحة |\n'
        )}
        _APP.ensure_gap_guide_coverage(
            sections_governance, 'ar', 'Cyber Security', 'NCA ECC')
        _APP.ensure_gap_guide_coverage(
            sections_iam, 'ar', 'Cyber Security', 'NCA ECC')
        guide_gov = sections_governance.get('gaps', '')
        guide_iam = sections_iam.get('gaps', '')
        # Guides must exist and differ
        self.assertIn('دليل', guide_gov,
                      'Governance gap should have an implementation guide')
        self.assertIn('دليل', guide_iam,
                      'IAM gap should have an implementation guide')


# ---------------------------------------------------------------------------
# Test 3: Roadmap mandatory columns
# ---------------------------------------------------------------------------

class TestRoadmapColumns(unittest.TestCase):
    """3. Roadmap must have at least 4 rows and activity/owner/timeline/deliverable."""

    @_skip_if_no_app
    def test_roadmap_has_required_columns(self):
        sections = {
            'roadmap': (
                '## 5. خارطة طريق التنفيذ\n\n'
                '| # | النشاط | المسؤول | الإطار الزمني | المخرج |\n'
                '|---|--------|---------|---------------|--------|\n'
            )
        }
        _APP.synthesize_roadmap_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
        )
        roadmap = sections.get('roadmap', '')
        n_rows = _APP._count_substantive_roadmap_rows(roadmap)
        self.assertGreaterEqual(
            n_rows, 4,
            f'Expected ≥4 roadmap rows, got {n_rows}',
        )
        # Check all 4 key column types are present
        hdr_re = re.compile(
            r'^\|\s*#\s*\|\s*(?:النشاط|Activity)\s*\|',
            re.IGNORECASE | re.MULTILINE,
        )
        self.assertIsNotNone(hdr_re.search(roadmap),
                             'Roadmap must have # | Activity/النشاط header')

    @_skip_if_no_app
    def test_roadmap_english_minimum_rows(self):
        sections = {'roadmap': ''}
        _APP.synthesize_roadmap_depth(
            sections, lang='en',
            domain='Cyber Security', fw_short='NCA ECC',
        )
        n_rows = _APP._count_substantive_roadmap_rows(sections.get('roadmap', ''))
        self.assertGreaterEqual(n_rows, 4, f'EN roadmap: expected ≥4 rows, got {n_rows}')


# ---------------------------------------------------------------------------
# Test 4: KPI table depth
# ---------------------------------------------------------------------------

class TestKpiDepth(unittest.TestCase):
    """4. KPI table must have ≥ 6 metrics after enforce_technical_strategy_depth
    in consulting mode.
    """

    @_skip_if_no_app
    def test_kpi_enriched_to_six_in_consulting_mode(self):
        sections = {
            'kpis': (
                '## 6. مؤشرات الأداء الرئيسية\n\n'
                '| # | وصف المؤشر | القيمة المستهدفة | صيغة الاحتساب | الإطار الزمني |\n'
                '|---|-------------|-----------------|----------------|----------------|\n'
                '| 1 | نسبة تطبيق الضوابط | ≥ 95% | (المطبّق ÷ الإجمالي) × 100 | خلال 12 شهراً |\n'
                '| 2 | نسبة إغلاق الفجوات | 100% | (المغلق ÷ الإجمالي) × 100 | خلال 9 أشهر |\n'
            )
        }
        _APP.enforce_technical_strategy_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
            generation_mode='consulting',
        )
        n_kpis = _APP.count_substantive_kpis(sections.get('kpis', ''))
        self.assertGreaterEqual(
            n_kpis, 6,
            f'Expected ≥6 KPI rows in consulting mode, got {n_kpis}',
        )

    @_skip_if_no_app
    def test_kpi_minimum_in_drafting_mode(self):
        sections = {'kpis': ''}
        _APP.enforce_technical_strategy_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
            generation_mode='drafting',
        )
        n_kpis = _APP.count_substantive_kpis(sections.get('kpis', ''))
        # In drafting mode, min is 4
        self.assertGreaterEqual(
            n_kpis, 4,
            f'Expected ≥4 KPI rows in drafting mode, got {n_kpis}',
        )


# ---------------------------------------------------------------------------
# Test 5: Risk table depth
# ---------------------------------------------------------------------------

class TestRiskTableDepth(unittest.TestCase):
    """5. Risk table must contain owner/treatment and ≥ 5 rows."""

    @_skip_if_no_app
    def test_risk_table_has_minimum_rows(self):
        sections = {'confidence': ''}
        _APP.synthesize_confidence_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
            org_name='Test Org', maturity='initial',
        )
        n_risks = _APP._count_risk_rows_with_mitigation(
            sections.get('confidence', ''))
        self.assertGreaterEqual(
            n_risks, 4,
            f'Expected ≥4 risk rows, got {n_risks}',
        )

    @_skip_if_no_app
    def test_risk_table_enriched_to_five_by_depth_pass(self):
        sections = {
            'confidence': (
                '## 7. تقييم الثقة والمخاطر\n\n'
                '**درجة الثقة:** 65%\n\n'
                '### المخاطر الرئيسية:\n\n'
                '| # | المخاطر | الاحتمالية | التأثير | خطة المعالجة |\n'
                '|---|--------|-----------|--------|-------------|\n'
                '| 1 | تأخر الميزانية | متوسط | عالٍ | جدولة المدفوعات مبكراً |\n'
            )
        }
        _APP.enforce_technical_strategy_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
            generation_mode='consulting',
        )
        n_risks = _APP._count_risk_rows_with_mitigation(
            sections.get('confidence', ''))
        self.assertGreaterEqual(
            n_risks, 5,
            f'Expected ≥5 risk rows after depth pass, got {n_risks}',
        )

    @_skip_if_no_app
    def test_risk_rows_have_mitigation_text(self):
        """Each risk row emitted by the synthesizer must have a mitigation plan
        (non-placeholder last cell, with a section filter to exclude CSF rows).
        """
        sections = {'confidence': ''}
        _APP.synthesize_confidence_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
        )
        conf = sections.get('confidence', '')
        # Only inspect rows that appear after the risk-table header
        risk_section_re = re.compile(
            r'###\s*(?:المخاطر الرئيسية|Key Risks)',
            re.IGNORECASE,
        )
        m = risk_section_re.search(conf)
        if not m:
            self.skipTest('No risk section header found; CSF section may be missing')
        risk_section = conf[m.start():]
        found_rows = 0
        for ln in risk_section.splitlines():
            s = ln.strip()
            if not (s.startswith('|') and s.endswith('|')):
                continue
            if re.match(r'^\|[\s\-:|]+\|$', s):
                continue
            cells = [c.strip() for c in s.split('|')[1:-1]]
            if cells and cells[0].replace('.', '').isdigit() and len(cells) >= 4:
                mitigation = cells[-1]
                self.assertTrue(
                    len(mitigation) > 10 and mitigation not in ('—', '-', 'TBD'),
                    f'Risk row {cells[0]} has no substantive mitigation: {mitigation!r}',
                )
                found_rows += 1
        self.assertGreater(found_rows, 0, 'No risk data rows found in confidence section')


# ---------------------------------------------------------------------------
# Test 6: No trace comments in content
# ---------------------------------------------------------------------------

class TestNoTraceComments(unittest.TestCase):
    """6. Preview/export content must not contain trace comments."""

    @_skip_if_no_app
    def test_synthesized_pillars_have_no_trace_comments(self):
        sections = {'pillars': ''}
        _APP.synthesize_pillars_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
        )
        self.assertFalse(
            _has_trace_comments(sections.get('pillars', '')),
            'Synthesized pillars contain trace comments',
        )

    @_skip_if_no_app
    def test_synthesized_kpis_have_no_trace_comments(self):
        sections = {'kpis': ''}
        _APP.synthesize_kpi_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
        )
        self.assertFalse(
            _has_trace_comments(sections.get('kpis', '')),
            'Synthesized KPIs contain trace comments',
        )

    @_skip_if_no_app
    def test_depth_enrichment_has_no_trace_comments(self):
        sections = {
            'vision': '',
            'pillars': (
                '## 2. الركائز الاستراتيجية\n\n'
                '### الركيزة الأولى: الحوكمة\n\n'
                'ركيزة الحوكمة.\n\n'
                '| # | المبادرة | الوصف | المخرج المتوقع |\n'
                '|---|---------|-------|----------------|\n'
                '| 1 | إنشاء لجنة الحوكمة | تشكيل اللجنة | الميثاق |\n\n'
            ),
            'gaps': '',
            'roadmap': '',
            'kpis': '',
            'confidence': '',
        }
        _APP.enforce_technical_strategy_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
        )
        for key, val in sections.items():
            self.assertFalse(
                _has_trace_comments(val),
                f'Section "{key}" contains trace comments after depth enrichment',
            )

    def test_strip_trace_comments_removes_all_variants(self):
        """_strip_trace_comments must handle both semicolon and pipe formats."""
        if not _USING_REAL_APP:
            self.skipTest('app.py not importable')
        old_style = '<!-- trace:section=vision|src=ai|key=row_1 -->'
        new_style = '<!-- trace:section=vision;src=ai;key=row_1 -->'
        self.assertEqual(
            _APP._strip_trace_comments(f'text {old_style} more'), 'text  more')
        self.assertEqual(
            _APP._strip_trace_comments(f'text {new_style} more'), 'text  more')


# ---------------------------------------------------------------------------
# Test 8: enforce_technical_strategy_depth return value
# ---------------------------------------------------------------------------

class TestDepthEnrichmentReturnValue(unittest.TestCase):
    """8. enforce_technical_strategy_depth returns correct summary dict."""

    @_skip_if_no_app
    def test_returns_dict_with_expected_keys(self):
        sections = {k: '' for k in
                    ('vision', 'pillars', 'environment', 'gaps',
                     'roadmap', 'kpis', 'confidence')}
        result = _APP.enforce_technical_strategy_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
        )
        self.assertIsInstance(result, dict)
        for key in ('pillar_initiatives_added', 'so_rows_added',
                    'kpi_rows_added', 'risk_rows_added', 'capability_gaps'):
            self.assertIn(key, result,
                          f'Missing key "{key}" in depth enrichment result')

    @_skip_if_no_app
    def test_idempotent_on_already_rich_sections(self):
        """Calling twice must not add duplicate rows."""
        sections = {k: '' for k in
                    ('vision', 'pillars', 'environment', 'gaps',
                     'roadmap', 'kpis', 'confidence')}
        _APP.enforce_technical_strategy_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
            generation_mode='consulting',
        )
        kpis_after_first = _APP.count_substantive_kpis(
            sections.get('kpis', ''))
        result2 = _APP.enforce_technical_strategy_depth(
            sections, lang='ar',
            domain='Cyber Security', fw_short='NCA ECC',
            generation_mode='consulting',
        )
        kpis_after_second = _APP.count_substantive_kpis(
            sections.get('kpis', ''))
        self.assertEqual(result2.get('kpi_rows_added', 0), 0,
                         'Second call should not add any KPI rows')
        self.assertEqual(kpis_after_first, kpis_after_second,
                         'KPI count should not change on second call')


# ---------------------------------------------------------------------------
# Test: validate_arabic_strategy_semantic_richness detects thin pillars
# ---------------------------------------------------------------------------

class TestValidatorPillarInitiativeCheck(unittest.TestCase):
    """validate_arabic_strategy_semantic_richness must flag pillars with
    fewer than 3 initiatives.
    """

    @_skip_if_no_app
    def test_thin_pillars_flagged(self):
        sections = {
            'vision': (
                '### الأهداف الاستراتيجية\n\n'
                '| # | الهدف | مؤشر الأداء | المبرر | الإطار الزمني |\n'
                '|---|-------|-------------|--------|---------------|\n'
                '| 1 | تعزيز الحوكمة | 100% | متطلب | خلال 12 شهراً |\n'
                '| 2 | تطبيق الضوابط | ≥95% | متطلب | خلال 12 شهراً |\n'
                '| 3 | مراقبة SIEM | MTTD≤60د | متطلب | خلال 9 أشهر |\n'
                '| 4 | التوعية | ≥90% | متطلب | خلال 12 شهراً |\n'
            ),
            'pillars': (
                '## 2. الركائز الاستراتيجية\n\n'
                '### الركيزة الأولى: الحوكمة\n\n'
                'نص الحوكمة\n\n'
                '| # | المبادرة | الوصف | المخرج المتوقع |\n'
                '|---|---------|-------|----------------|\n'
                '| 1 | لجنة الحوكمة | تشكيل اللجنة | الميثاق |\n\n'
                '### الركيزة الثانية: الحماية\n\n'
                'نص الحماية\n\n'
                '| # | المبادرة | الوصف | المخرج المتوقع |\n'
                '|---|---------|-------|----------------|\n'
                '| 1 | نشر EDR | تطبيق EDR | سجل الجهاز |\n\n'
                '### الركيزة الثالثة: الاستجابة\n\n'
                'نص الاستجابة\n\n'
                '| # | المبادرة | الوصف | المخرج المتوقع |\n'
                '|---|---------|-------|----------------|\n'
                '| 1 | SIEM | ربط مصادر | كتالوج |\n\n'
            ),
            'environment': 'فقرة بيئية كافية ' * 20,
            'gaps': (
                '| # | الفجوة | الوصف | الأولوية | الحالة |\n'
                '|---|-------|-------|---------|--------|\n'
                '| 1 | الحوكمة | غياب اللجنة | حرجة | مفتوحة |\n'
                '| 2 | IAM | غياب PAM | عالية | مفتوحة |\n'
            ),
            'roadmap': (
                '| # | النشاط | المسؤول | الإطار الزمني | المخرج |\n'
                '|---|--------|---------|---------------|--------|\n'
                '| 1 | الحوكمة | CISO | الشهر 1-3 | الميثاق |\n'
                '| 2 | IAM | IT | الشهر 3-6 | خطة IAM |\n'
                '| 3 | SIEM | SOC | الشهر 4-9 | كتالوج |\n'
                '| 4 | التوعية | HR | الشهر 6-12 | التقارير |\n'
            ),
            'kpis': (
                '| # | وصف المؤشر | القيمة المستهدفة | صيغة الاحتساب | الإطار الزمني |\n'
                '|---|-------------|-----------------|----------------|----------------|\n'
                '| 1 | ضوابط | ≥95% | حساب | خلال 12 شهراً |\n'
                '| 2 | توعية | ≥90% | حساب | خلال 9 أشهر |\n'
                '| 3 | حوادث | ≤4 | حساب | خلال 6 أشهر |\n'
                '| 4 | ثغرات | 100% | حساب | خلال 6 أشهر |\n'
            ),
            'confidence': (
                '**درجة الثقة:** 65%\n\n'
                '### مبررات التقييم\n\n'
                'مبررات كافية لتقييم الثقة بناءً على الفجوات المشخّصة.\n\n'
                '### عوامل النجاح الحرجة:\n\n'
                '| # | العامل | الوصف | الأهمية |\n'
                '|---|-------|-------|--------|\n'
                '| 1 | دعم القيادة | الإدارة العليا | حرج |\n'
                '| 2 | الموارد | كفاءات متخصصة | عالٍ |\n'
                '| 3 | الميزانية | تمويل كافٍ | عالٍ |\n'
                '| 4 | التكنولوجيا | أدوات متكاملة | متوسط |\n'
                '### المخاطر الرئيسية:\n\n'
                '| # | المخاطر | الاحتمالية | التأثير | خطة المعالجة |\n'
                '|---|--------|-----------|--------|-------------|\n'
                '| 1 | تأخر | متوسط | عالٍ | معالجة التأخر |\n'
                '| 2 | ميزانية | متوسط | عالٍ | جدولة الميزانية |\n'
                '| 3 | كفاءات | عالٍ | عالٍ | التوظيف المبكر |\n'
                '| 4 | مقاومة | متوسط | متوسط | إدارة التغيير |\n'
            ),
        }
        defects = _APP.validate_arabic_strategy_semantic_richness(
            sections, lang='ar', doc_subtype='technical')
        defect_tags = [d[0] for d in defects]
        self.assertIn(
            'pillar_initiatives_insufficient', defect_tags,
            f'Expected pillar_initiatives_insufficient defect; got: {defect_tags}',
        )

    @_skip_if_no_app
    def test_rich_pillars_not_flagged(self):
        """Pillars with ≥3 initiatives each must not trigger the defect."""
        three_init = (
            '| # | المبادرة | الوصف | المخرج المتوقع |\n'
            '|---|---------|-------|----------------|\n'
            '| 1 | مبادرة أ | وصف أ | مخرج أ |\n'
            '| 2 | مبادرة ب | وصف ب | مخرج ب |\n'
            '| 3 | مبادرة ج | وصف ج | مخرج ج |\n'
        )
        pillars = (
            '## 2. الركائز الاستراتيجية\n\n'
            f'### الركيزة الأولى: الحوكمة\n\nنص\n\n{three_init}\n'
            f'### الركيزة الثانية: الحماية\n\nنص\n\n{three_init}\n'
            f'### الركيزة الثالثة: الاستجابة\n\nنص\n\n{three_init}\n'
        )
        sections = {
            'vision': (
                '| # | الهدف | مؤشر الأداء | المبرر | الإطار الزمني |\n'
                '|---|-------|-------------|--------|---------------|\n'
                '| 1 | هدف 1 | 100% | مبرر | خلال 12 شهراً |\n'
                '| 2 | هدف 2 | ≥95% | مبرر | خلال 12 شهراً |\n'
                '| 3 | هدف 3 | MTTD≤60د | مبرر | خلال 9 أشهر |\n'
                '| 4 | هدف 4 | ≥90% | مبرر | خلال 12 شهراً |\n'
            ),
            'pillars': pillars,
            'environment': 'فقرة بيئية كافية ' * 20,
            'gaps': (
                '| # | الفجوة | الوصف | الأولوية | الحالة |\n'
                '|---|-------|-------|---------|--------|\n'
                '| 1 | الحوكمة | وصف | حرجة | مفتوحة |\n'
                '| 2 | IAM | وصف | عالية | مفتوحة |\n'
            ),
            'roadmap': (
                '| # | النشاط | المسؤول | الإطار الزمني | المخرج |\n'
                '|---|--------|---------|---------------|--------|\n'
                '| 1 | نشاط 1 | CISO | الشهر 1-3 | مخرج 1 |\n'
                '| 2 | نشاط 2 | IT | الشهر 3-6 | مخرج 2 |\n'
                '| 3 | نشاط 3 | SOC | الشهر 4-9 | مخرج 3 |\n'
                '| 4 | نشاط 4 | HR | الشهر 6-12 | مخرج 4 |\n'
            ),
            'kpis': (
                '| # | وصف المؤشر | القيمة المستهدفة | صيغة الاحتساب | الإطار الزمني |\n'
                '|---|-------------|-----------------|----------------|----------------|\n'
                '| 1 | مؤشر 1 | ≥95% | (أ÷ب)×100 | خلال 12 شهراً |\n'
                '| 2 | مؤشر 2 | ≥90% | (أ÷ب)×100 | خلال 9 أشهر |\n'
                '| 3 | مؤشر 3 | ≤4 | (أ÷ب)×100 | خلال 6 أشهر |\n'
                '| 4 | مؤشر 4 | 100% | (أ÷ب)×100 | خلال 6 أشهر |\n'
            ),
            'confidence': (
                '**درجة الثقة:** 65%\n\n'
                '### مبررات التقييم\n\nمبررات.\n\n'
                '### عوامل النجاح الحرجة:\n\n'
                '| # | العامل | الوصف | الأهمية |\n'
                '|---|-------|-------|--------|\n'
                '| 1 | دعم | وصف | حرج |\n'
                '| 2 | موارد | وصف | عالٍ |\n'
                '| 3 | ميزانية | وصف | عالٍ |\n'
                '| 4 | تقنية | وصف | متوسط |\n'
                '### المخاطر الرئيسية:\n\n'
                '| # | المخاطر | الاحتمالية | التأثير | خطة المعالجة |\n'
                '|---|--------|-----------|--------|-------------|\n'
                '| 1 | خطر 1 | متوسط | عالٍ | معالجة 1 |\n'
                '| 2 | خطر 2 | متوسط | عالٍ | معالجة 2 |\n'
                '| 3 | خطر 3 | عالٍ | عالٍ | معالجة 3 |\n'
                '| 4 | خطر 4 | متوسط | متوسط | معالجة 4 |\n'
            ),
        }
        defects = _APP.validate_arabic_strategy_semantic_richness(
            sections, lang='ar', doc_subtype='technical')
        defect_tags = [d[0] for d in defects]
        self.assertNotIn(
            'pillar_initiatives_insufficient', defect_tags,
            f'Rich pillars should not trigger defect; all defects: {defect_tags}',
        )


if __name__ == '__main__':
    print(f'Using real app.py: {_USING_REAL_APP}')
    unittest.main(verbosity=2)
