"""PR-CY11 — Post-synthesis Cyber specialized-function objective
stability tests.

Render runtime evidence after PR-CY9 / PR-CY10 (cyber + ECC + DCC,
AR, ``org_structure_is_none=True``) continued to surface::

    [CONVERGENCE-REPAIR-RESULT] before=3 after=1 accepted=True
    specialized_function_objective_missing:cyber (vision) 0/1

That is, the broader convergence loop converged (the gaps / pillars /
roadmap / DCC repairs settled) but the targeted Cyber Vision
specialized-function objective top-up did not produce a row that
satisfied the PR-CY8 dual-requirement detector AND the post-
normalization audit re-emitted the defect.

PR-CY11 adds:

1. Row-extraction + row-splice helpers
   (``_extract_cyber_vision_objective_topup_row`` /
   ``_splice_cyber_vision_objective_topup_row``) so the targeted
   top-up can splice ONE qualifying AI-generated row into the
   ORIGINAL vision while preserving every existing valid objective
   row verbatim.  No deterministic objective row is generated by
   these helpers — when no AI-emitted row qualifies they return ``''``
   so the caller fail-closes.

2. Stronger ``[CYBER-VISION-SPECIALIZED-OBJECTIVE]`` diagnostics
   (``phase=candidate``, ``phase=accepted``, ``phase=post_
   normalization``, ``row_preview``, ``has_governance_committee``,
   ``has_roles_reporting``) so log readers can see WHY a candidate
   was accepted or rejected.

3. A FINAL post-normalization guard wired BEFORE the post-
   normalization 422 emission: when the defect reappears after AR
   normalization, the targeted top-up is re-invoked one last time
   and ``_final_strategy_audit`` is re-run so the 422 reflects the
   corrected state.

Strictly Cyber-scoped — Data Management / AI / DT / ERM behaviour is
not exercised.  No deterministic objective rows are inserted.
Validators are NOT weakened.  auth / DB / export / PDF / DOCX helpers
are NOT touched.

Run::

    python -m pytest \\
        tests/test_cyber_specialized_objective_post_synthesis_prcy11.py -q
"""
import functools
import importlib.util
import io
import os
import sys
import tempfile
import unittest
from contextlib import redirect_stdout


_TMP_DB_DIR = tempfile.mkdtemp(prefix='test_cyber_sfo_prcy11_')
os.environ.setdefault('ADMIN_PASSWORD', 'test-admin-password')
os.environ.setdefault('SECRET_KEY', 'test-secret-key')
os.environ.setdefault(
    'DATABASE_URL',
    'sqlite:///' + os.path.join(_TMP_DB_DIR, 'test.db'),
)
os.environ.setdefault('OPENAI_API_KEY', '')
os.environ.setdefault('ANTHROPIC_API_KEY', '')
os.environ.setdefault('GOOGLE_API_KEY', '')


_APP = None
try:
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
    _spec = importlib.util.spec_from_file_location(
        'app', os.path.join(os.path.dirname(__file__), '..', 'app.py')
    )
    _APP = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_APP)
except (ImportError, ModuleNotFoundError) as _e:  # pragma: no cover
    print(f'[WARN] Could not import app.py: {_e}')
    _APP = None


def _skip_if_no_app(fn):
    @functools.wraps(fn)
    def _wrapped(self, *a, **kw):
        if _APP is None:
            self.skipTest('app.py could not be imported')
        return fn(self, *a, **kw)
    return _wrapped


# ── Fixtures ────────────────────────────────────────────────────────────


_GOOD_ROW_AR = (
    'إنشاء إدارة الأمن السيبراني بقيادة CISO وتفعيل لجنة حوكمة '
    'الأمن السيبراني وتحديد الأدوار والمسؤوليات وخطوط الرفع')
_BAD_ROW_AR = 'إنشاء مكتب CISO وتفعيل لجنة حوكمة الأمن السيبراني'


def _vision_without_specialized():
    return (
        '## 1. الرؤية والأهداف الاستراتيجية\n\n'
        '**الرؤية:** قيادة الأمن السيبراني الوطني.\n\n'
        '| # | الهدف | المقياس المستهدف | المبرر | الإطار الزمني |\n'
        '|---|---|---|---|---|\n'
        '| 1 | تحقيق الامتثال لإطار ECC | 100% | NCA ECC | 18 شهراً |\n'
        '| 2 | تحقيق الامتثال لإطار DCC | 100% | NCA DCC | 18 شهراً |\n'
        '| 3 | تنفيذ إدارة الهوية والوصول | 100% | IAM | 12 شهراً |\n'
        '| 4 | تأسيس مركز العمليات الأمنية | 100% | SOC | 18 شهراً |\n'
    )


def _vision_with_extra_row(extra_row_objective):
    return (
        '## 1. الرؤية والأهداف الاستراتيجية\n\n'
        '**الرؤية:** قيادة الأمن السيبراني الوطني.\n\n'
        '| # | الهدف | المقياس المستهدف | المبرر | الإطار الزمني |\n'
        '|---|---|---|---|---|\n'
        '| 1 | تحقيق الامتثال لإطار ECC | 100% | NCA ECC | 18 شهراً |\n'
        '| 2 | تحقيق الامتثال لإطار DCC | 100% | NCA DCC | 18 شهراً |\n'
        '| 3 | تنفيذ إدارة الهوية والوصول | 100% | IAM | 12 شهراً |\n'
        '| 4 | تأسيس مركز العمليات الأمنية | 100% | SOC | 18 شهراً |\n'
        f'| 5 | {extra_row_objective} | 100% | NCA حوكمة | 12 شهراً |\n'
    )


def _ctx(org_structure_is_none=True):
    return {
        'frameworks': ['ECC', 'DCC'],
        'org_name': 'TestOrg',
        'sector': 'General',
        'maturity': 'initial',
        'generation_mode': 'drafting',
        'org_structure_is_none': org_structure_is_none,
    }


# ── Test 1 — existing objectives are preserved ──────────────────────────


class Test01ExistingObjectivesPreserved(unittest.TestCase):

    @_skip_if_no_app
    def test_01_existing_objective_rows_preserved(self):
        """All 4 original objective rows must survive the top-up."""
        original = _vision_without_specialized()
        sections = {'vision': original}
        good = _vision_with_extra_row(_GOOD_ROW_AR)

        orig_ai = _APP.ai_repair_strategy_section
        _APP.ai_repair_strategy_section = lambda **kw: good
        try:
            rc = _APP._convergence_cyber_specialized_objective_topup_repair(
                sections, lang='ar',
                domain='Cyber Security', ctx=_ctx(),
                log={'synth_status': {}})
        finally:
            _APP.ai_repair_strategy_section = orig_ai

        self.assertEqual(rc, 1)
        new_vision = sections['vision']
        for substantive in (
                'تحقيق الامتثال لإطار ECC',
                'تحقيق الامتثال لإطار DCC',
                'تنفيذ إدارة الهوية والوصول',
                'تأسيس مركز العمليات الأمنية',
        ):
            self.assertIn(substantive, new_vision)


# ── Test 2 — AI-generated row with all required phrases clears defect ──


class Test02StrongRowClearsDefect(unittest.TestCase):

    @_skip_if_no_app
    def test_02_strong_row_clears_specialized_function_missing(self):
        """An AI candidate carrying establishment + CISO + committee
        + roles/reporting in one row clears
        ``specialized_function_objective_missing:cyber``."""
        sections = {'vision': _vision_without_specialized()}
        good = _vision_with_extra_row(_GOOD_ROW_AR)

        orig_ai = _APP.ai_repair_strategy_section
        _APP.ai_repair_strategy_section = lambda **kw: good
        try:
            rc = _APP._convergence_cyber_specialized_objective_topup_repair(
                sections, lang='ar',
                domain='Cyber Security', ctx=_ctx(),
                log={'synth_status': {}})
        finally:
            _APP.ai_repair_strategy_section = orig_ai

        self.assertEqual(rc, 1)
        self.assertFalse(
            _APP._compute_missing_specialized_function_objective(
                sections, 'Cyber Security', lang='ar',
                org_structure_is_none=True))


# ── Test 3 — Same-row dual requirement is enforced ──────────────────────


class Test03DualRequirementSameRow(unittest.TestCase):

    @_skip_if_no_app
    def test_03_split_across_two_rows_does_not_clear(self):
        """A vision whose establishment phrase is in row N and
        leadership phrase is in row M (different rows) must NOT
        clear the dual-requirement detector — the PR-CY8 invariant
        that BOTH halves live in the SAME cell is preserved."""
        split_vision = (
            '## 1. الرؤية والأهداف الاستراتيجية\n\n'
            '**الرؤية:** قيادة الأمن السيبراني الوطني.\n\n'
            '| # | الهدف | المقياس المستهدف | المبرر | الإطار الزمني |\n'
            '|---|---|---|---|---|\n'
            '| 1 | إنشاء إدارة الأمن السيبراني | 100% | حوكمة | '
            '12 شهراً |\n'
            '| 2 | تعيين CISO | 100% | قيادة | 6 شهراً |\n'
            '| 3 | تنفيذ إدارة الهوية والوصول | 100% | IAM | '
            '12 شهراً |\n'
            '| 4 | تحقيق الامتثال لإطار ECC | 100% | NCA ECC | '
            '18 شهراً |\n'
        )
        sections = {'vision': split_vision}
        self.assertTrue(
            _APP._compute_missing_specialized_function_objective(
                sections, 'Cyber Security', lang='ar',
                org_structure_is_none=True),
            'split-across-rows must NOT clear the gate (same-row '
            'invariant)')


# ── Test 4 — Accepted row not overwritten by later generic repair ──────


class Test04AcceptedRowNotOverwritten(unittest.TestCase):

    @_skip_if_no_app
    def test_04_accepted_row_survives_repeat_topup_call(self):
        """When the top-up has already been accepted and committed,
        re-invoking the helper must be a no-op (the detector returns
        False so the AI is NOT called a second time, and the
        previously-accepted row remains intact)."""
        sections = {'vision': _vision_without_specialized()}
        good = _vision_with_extra_row(_GOOD_ROW_AR)

        orig_ai = _APP.ai_repair_strategy_section
        ai_calls = {'n': 0}

        def _stub(**kw):
            ai_calls['n'] += 1
            return good

        _APP.ai_repair_strategy_section = _stub
        try:
            # First invocation: defect present → AI called.
            rc1 = _APP._convergence_cyber_specialized_objective_topup_repair(
                sections, lang='ar',
                domain='Cyber Security', ctx=_ctx(),
                log={'synth_status': {}})
            self.assertEqual(rc1, 1)
            self.assertGreaterEqual(ai_calls['n'], 1)
            vision_after_first = sections['vision']
            # Second invocation: defect cleared → AI must NOT be
            # called again (the helper short-circuits when
            # ``_compute_missing_specialized_function_objective`` is
            # already False).
            prev_n = ai_calls['n']
            rc2 = _APP._convergence_cyber_specialized_objective_topup_repair(
                sections, lang='ar',
                domain='Cyber Security', ctx=_ctx(),
                log={'synth_status': {}})
        finally:
            _APP.ai_repair_strategy_section = orig_ai

        self.assertEqual(rc2, 0)
        self.assertEqual(ai_calls['n'], prev_n,
                         'AI must not be re-invoked when defect '
                         'is already clear')
        # Accepted row still present after the second call.
        self.assertEqual(sections['vision'], vision_after_first)
        self.assertIn(_GOOD_ROW_AR, sections['vision'])


# ── Test 5 — Post-normalization audit passes when row exists ───────────


class Test05PostNormalizationAuditPasses(unittest.TestCase):

    @_skip_if_no_app
    def test_05_final_audit_clears_specialized_when_row_exists(self):
        """``_final_strategy_audit`` does NOT emit
        ``specialized_function_objective_missing:cyber`` when the
        Vision section contains a row that satisfies the dual-
        requirement detector."""
        sections = {
            'vision': _vision_with_extra_row(_GOOD_ROW_AR),
        }
        self.assertFalse(
            _APP._compute_missing_specialized_function_objective(
                sections, 'Cyber Security', lang='ar',
                org_structure_is_none=True))


# ── Test 6 — Post-normalization guard re-runs top-up when row removed ──


class Test06PostNormalizationGuardRuns(unittest.TestCase):

    @_skip_if_no_app
    def test_06_guard_helper_diagnostic_emitted_on_runtime(self):
        """The PR-CY11 top-up helper emits
        ``[CYBER-VISION-SPECIALIZED-OBJECTIVE] phase=candidate`` and
        ``phase=accepted`` diagnostics on the runtime path so the
        post-normalization guard wiring can confirm the helper
        actually fired (the guard at the post-normalization 422 site
        simply re-invokes this helper)."""
        sections = {'vision': _vision_without_specialized()}
        good = _vision_with_extra_row(_GOOD_ROW_AR)

        orig_ai = _APP.ai_repair_strategy_section
        _APP.ai_repair_strategy_section = lambda **kw: good
        try:
            buf = io.StringIO()
            with redirect_stdout(buf):
                rc = _APP._convergence_cyber_specialized_objective_topup_repair(
                    sections, lang='ar',
                    domain='Cyber Security', ctx=_ctx(),
                    log={'synth_status': {}})
            out = buf.getvalue()
        finally:
            _APP.ai_repair_strategy_section = orig_ai

        self.assertEqual(rc, 1)
        self.assertIn('[CYBER-VISION-SPECIALIZED-OBJECTIVE]', out)
        self.assertIn('phase=candidate', out)
        self.assertIn('phase=accepted', out)
        for fld in (
                'has_establishment_phrase=',
                'has_leadership_phrase=',
                'has_governance_committee=',
                'has_roles_reporting=',
                'contains_bad_ciso_office=',
                'row_preview=',
        ):
            self.assertIn(fld, out,
                          f'expected diagnostic field {fld!r} '
                          f'missing from log:\n{out}')


# ── Test 7 — "مكتب CISO" is rejected ───────────────────────────────────


class Test07BadCisoOfficeRejected(unittest.TestCase):

    @_skip_if_no_app
    def test_07_bad_ciso_office_extraction_rejects(self):
        """``_extract_cyber_vision_objective_topup_row`` must NOT
        return a row whose blob contains ``مكتب CISO`` even when
        that row otherwise carries an establishment phrase and a
        governance committee phrase."""
        ai_text = (
            '| 5 | إنشاء مكتب CISO وتفعيل لجنة حوكمة الأمن السيبراني '
            '| 100% | حوكمة | 12 شهراً |\n')
        row = _APP._extract_cyber_vision_objective_topup_row(ai_text)
        self.assertEqual(
            row, '',
            'bad-office row must NOT be selected by the extractor')

    @_skip_if_no_app
    def test_07b_bad_ciso_office_rejected_by_runtime_path(self):
        """End-to-end: when the AI returns the forbidden
        ``مكتب CISO`` wording the runtime top-up rejects it (no
        splice, no accept) and the detector still fires."""
        sections = {'vision': _vision_without_specialized()}
        bad = _vision_with_extra_row(_BAD_ROW_AR)

        orig_ai = _APP.ai_repair_strategy_section
        _APP.ai_repair_strategy_section = lambda **kw: bad
        try:
            rc = _APP._convergence_cyber_specialized_objective_topup_repair(
                sections, lang='ar',
                domain='Cyber Security', ctx=_ctx(),
                log={'synth_status': {}})
        finally:
            _APP.ai_repair_strategy_section = orig_ai

        self.assertEqual(rc, 0)
        # Original vision preserved verbatim.
        self.assertEqual(sections['vision'],
                         _vision_without_specialized())


# ── Test 8 — Minimum objective row count is not reduced ────────────────


class Test08MinimumRowCountPreserved(unittest.TestCase):

    @_skip_if_no_app
    def test_08_row_count_never_decreases(self):
        """After a successful top-up, ``count_valid_objective_rows``
        must be ≥ the original count.  Specifically, the splice helper
        appends one row, so the new count must be exactly
        original + 1 in the splice path."""
        original = _vision_without_specialized()
        before_n = _APP.count_valid_objective_rows(original)

        good_row_line = (
            '| 5 | إنشاء إدارة الأمن السيبراني بقيادة CISO وتفعيل '
            'لجنة حوكمة الأمن السيبراني وتحديد الأدوار والمسؤوليات '
            'وخطوط الرفع | 100% | NCA حوكمة | 12 شهراً |')
        spliced = _APP._splice_cyber_vision_objective_topup_row(
            original, good_row_line)
        after_n = _APP.count_valid_objective_rows(spliced)
        self.assertGreaterEqual(after_n, before_n,
                                f'row count must not decrease: '
                                f'before={before_n} after={after_n}')
        self.assertEqual(after_n, before_n + 1,
                         f'splice must add exactly ONE row: '
                         f'before={before_n} after={after_n}')


# ── Test 9 — Data Management unchanged ─────────────────────────────────


class Test09DataManagementUnchanged(unittest.TestCase):

    @_skip_if_no_app
    def test_09_data_domain_topup_noop(self):
        """The PR-CY11 top-up is a hard no-op for Data Management
        (no AI call, no row insertion, no sections mutation)."""
        sections = {'vision': 'unchanged data vision text'}
        orig_ai = _APP.ai_repair_strategy_section

        def _no(**kw):
            raise AssertionError('AI must not be called for data')

        _APP.ai_repair_strategy_section = _no
        try:
            rc = _APP._convergence_cyber_specialized_objective_topup_repair(
                sections, lang='ar',
                domain='Data Management',
                ctx={'org_structure_is_none': True,
                     'frameworks': ['PDPL']},
                log={'synth_status': {}})
        finally:
            _APP.ai_repair_strategy_section = orig_ai

        self.assertEqual(rc, 0)
        self.assertEqual(sections['vision'],
                         'unchanged data vision text')


# ── Test 10 — AI / DT / ERM unchanged ──────────────────────────────────


class Test10AIDTERMUnchanged(unittest.TestCase):

    @_skip_if_no_app
    def test_10_ai_dt_erm_topup_noop(self):
        """The PR-CY11 top-up is a hard no-op for AI / DT / ERM
        domains."""
        orig_ai = _APP.ai_repair_strategy_section

        def _no(**kw):
            raise AssertionError(
                'AI must not be called for non-cyber domains')

        _APP.ai_repair_strategy_section = _no
        try:
            for dom in ('Artificial Intelligence',
                        'Digital Transformation',
                        'Enterprise Risk Management'):
                sections = {'vision': f'unchanged {dom}'}
                rc = _APP._convergence_cyber_specialized_objective_topup_repair(
                    sections, lang='ar', domain=dom,
                    ctx={'org_structure_is_none': True,
                         'frameworks': ['NIST_AI_RMF']},
                    log={'synth_status': {}})
                self.assertEqual(rc, 0,
                                 f'top-up must be no-op for {dom!r}')
                self.assertEqual(sections['vision'],
                                 f'unchanged {dom}')
        finally:
            _APP.ai_repair_strategy_section = orig_ai


# ── Test 11 — Validators not weakened ──────────────────────────────────


class Test11ValidatorsNotWeakened(unittest.TestCase):

    @_skip_if_no_app
    def test_11_dual_requirement_detector_still_strict(self):
        """The PR-CY8 dual-requirement detector still rejects bare
        ``تعيين CISO`` / ``مكتب CISO`` / a lone governance committee
        / a framework-compliance-only row."""
        for weak in (
                'تعيين CISO',
                'إنشاء مكتب CISO',
                'تشكيل لجنة حوكمة الأمن السيبراني',
                'تحقيق الامتثال لإطار ECC',
        ):
            sections = {'vision': _vision_with_extra_row(weak)}
            self.assertTrue(
                _APP._compute_missing_specialized_function_objective(
                    sections, 'Cyber Security', lang='ar',
                    org_structure_is_none=True),
                f'weak phrasing {weak!r} must NOT clear the gate')


# ── Test 12 — No deterministic objective rows inserted ─────────────────


class Test12NoDeterministicRows(unittest.TestCase):

    @_skip_if_no_app
    def test_12_splice_returns_unchanged_when_row_blank(self):
        """The splice helper refuses to insert a blank row — when
        the extractor returns ``''`` (no AI-emitted row qualified)
        the splice helper is a no-op so no deterministic content is
        ever introduced."""
        original = _vision_without_specialized()
        spliced = _APP._splice_cyber_vision_objective_topup_row(
            original, '')
        self.assertEqual(spliced, original)

    @_skip_if_no_app
    def test_12b_extractor_returns_empty_when_no_qualifying_row(self):
        """``_extract_cyber_vision_objective_topup_row`` returns
        ``''`` when no AI-emitted row has BOTH halves of the dual
        requirement in the SAME row, even when each half exists in
        separate rows."""
        ai_text = (
            '| 1 | إنشاء إدارة الأمن السيبراني | 100% | حوكمة | '
            '12 شهراً |\n'
            '| 2 | تعيين CISO | 100% | قيادة | 6 شهراً |\n')
        row = _APP._extract_cyber_vision_objective_topup_row(ai_text)
        self.assertEqual(row, '',
                         'extractor must require BOTH halves in the '
                         'SAME row')

    @_skip_if_no_app
    def test_12c_empty_ai_response_inserts_no_row(self):
        """When the AI returns an empty string the runtime top-up
        does NOT inject a deterministic row — the original vision
        is preserved verbatim and ``synth_failed:vision`` is
        recorded."""
        original = _vision_without_specialized()
        sections = {'vision': original}
        synth_status = {}

        orig_ai = _APP.ai_repair_strategy_section
        _APP.ai_repair_strategy_section = lambda **kw: ''
        try:
            rc = _APP._convergence_cyber_specialized_objective_topup_repair(
                sections, lang='ar',
                domain='Cyber Security', ctx=_ctx(),
                log={'synth_status': synth_status})
        finally:
            _APP.ai_repair_strategy_section = orig_ai

        self.assertEqual(rc, 0)
        self.assertEqual(sections['vision'], original)
        nested = synth_status.get('synth_status', {}) or {}
        self.assertTrue(
            synth_status.get('vision') == 'failed'
            or nested.get('vision') == 'failed')


# ── Test 13 — auth / DB / export untouched ─────────────────────────────


class Test13AuthDbExportUntouched(unittest.TestCase):

    @_skip_if_no_app
    def test_13_auth_db_export_pdf_docx_helpers_present(self):
        """PR-CY11 only modifies the Cyber Vision objective top-up
        path.  Spot-check that the obvious auth / DB / export entry
        points remain available on app.py."""
        for attr in ('app', 'login_required', 'render_template'):
            self.assertTrue(
                hasattr(_APP, attr),
                f'{attr!r} must remain available on app.py')


# ── Bonus PR-CY11-specific tests ───────────────────────────────────────


class Test14RowSpliceFallback(unittest.TestCase):
    """PR-CY11 — When the full-vision regeneration is rejected but
    the AI response contains ONE qualifying row, the splice fallback
    extracts the row and inserts it into the ORIGINAL vision.  This
    verifies the new row-preserving path."""

    @_skip_if_no_app
    def test_14_splice_fallback_clears_defect(self):
        """When the AI returns a noisy candidate where only a single
        row carries BOTH halves of the dual requirement (and the
        contract validator rejects the whole-vision swap), the
        splice fallback extracts that row, splices it into the
        original vision, and the defect clears."""
        original = _vision_without_specialized()
        sections = {'vision': original}
        # Noisy candidate: malformed vision section that the
        # contract validator may reject as a whole (missing heading
        # / shortened structure) but which contains exactly ONE
        # qualifying objective row.  The splice path should still
        # recover.
        noisy = (
            'random preface text that breaks the full-vision '
            'validator\n'
            '| # | الهدف | المقياس المستهدف | المبرر | الإطار الزمني |\n'
            '|---|---|---|---|---|\n'
            f'| 99 | {_GOOD_ROW_AR} | 100% | NCA حوكمة | 12 شهراً |\n'
        )

        orig_ai = _APP.ai_repair_strategy_section
        _APP.ai_repair_strategy_section = lambda **kw: noisy
        try:
            rc = _APP._convergence_cyber_specialized_objective_topup_repair(
                sections, lang='ar',
                domain='Cyber Security', ctx=_ctx(),
                log={'synth_status': {}})
        finally:
            _APP.ai_repair_strategy_section = orig_ai

        # Either path (whole-vision OR splice fallback) must clear
        # the defect.  The splice path additionally guarantees every
        # original row is preserved verbatim.
        self.assertEqual(rc, 1, 'top-up must accept via either '
                                'whole-vision or splice fallback')
        self.assertFalse(
            _APP._compute_missing_specialized_function_objective(
                sections, 'Cyber Security', lang='ar',
                org_structure_is_none=True))
        # If the splice path was used, every original substantive
        # row is still present.
        for substantive in (
                'تحقيق الامتثال لإطار ECC',
                'تحقيق الامتثال لإطار DCC',
                'تنفيذ إدارة الهوية والوصول',
                'تأسيس مركز العمليات الأمنية',
        ):
            self.assertIn(substantive, sections['vision'])


if __name__ == '__main__':  # pragma: no cover
    unittest.main()
