"""Framework control catalog — capability_family granularity unless control_id set.

Do not describe this catalog as full control-level or complete regulatory coverage.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

FRAMEWORK_CATALOG: List[Dict[str, Any]] = [
    {
        'framework_id': 'nca_ecc',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'cyber_governance',
        'requirement_intent': 'Establish cyber governance and CISO accountability',
        'evidence_examples': ['CISO charter', 'Cyber committee minutes'],
        'typical_owner': 'CISO',
        'mapped_output_sections': ['vision_objectives', 'governance', 'roadmap'],
        'applicable_domains': ['cyber'],
        'label_ar': 'الضوابط الأساسية للأمن السيبراني',
        'label_en': 'NCA Essential Cybersecurity Controls',
    },
    {
        'framework_id': 'nca_dcc',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'data_cyber_protection',
        'requirement_intent': 'Protect and classify data assets',
        'evidence_examples': ['Data classification policy', 'DLP logs'],
        'typical_owner': 'DPO',
        'mapped_output_sections': ['roadmap', 'kpi_kri'],
        'applicable_domains': ['cyber', 'data_management'],
        'label_ar': 'ضوابط حماية البيانات',
        'label_en': 'NCA Data Cybersecurity Controls',
    },
    {
        'framework_id': 'nca_cscc',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'critical_systems',
        'requirement_intent': 'Protect critical national systems',
        'evidence_examples': ['Critical asset inventory'],
        'typical_owner': 'CISO',
        'mapped_output_sections': ['roadmap', 'risk'],
        'applicable_domains': ['cyber'],
        'label_ar': 'ضوابط الأنظمة الحساسة',
        'label_en': 'NCA Critical Systems Cybersecurity Controls',
    },
    {
        'framework_id': 'nca_ccc',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'cloud_security',
        'requirement_intent': 'Secure cloud workloads and shared responsibility',
        'evidence_examples': ['CSPM reports', 'Cloud architecture review'],
        'typical_owner': 'Cloud Security Lead',
        'mapped_output_sections': ['environment', 'roadmap'],
        'applicable_domains': ['cyber', 'digital_transformation'],
        'label_ar': 'ضوابط الحوسبة السحابية',
        'label_en': 'NCA Cloud Cybersecurity Controls',
    },
    {
        'framework_id': 'nca_tcc',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'telecom_security',
        'requirement_intent': 'Telecom sector cybersecurity baseline',
        'evidence_examples': ['Telecom SOC integration'],
        'typical_owner': 'CISO',
        'mapped_output_sections': ['roadmap'],
        'applicable_domains': ['cyber'],
        'label_ar': 'ضوابط قطاع الاتصالات',
        'label_en': 'NCA Telecom Cybersecurity Controls',
    },
    {
        'framework_id': 'ndmo',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'data_governance',
        'requirement_intent': 'National data management and governance',
        'evidence_examples': ['Data office charter', 'DG committee'],
        'typical_owner': 'CDO',
        'mapped_output_sections': ['vision_objectives', 'governance'],
        'applicable_domains': ['data_management'],
        'label_ar': 'الإطار الوطني لإدارة البيانات',
        'label_en': 'NDMO Data Governance',
    },
    {
        'framework_id': 'dga',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'digital_government',
        'requirement_intent': 'Digital government transformation alignment',
        'evidence_examples': ['Service digitisation KPIs'],
        'typical_owner': 'CDO',
        'mapped_output_sections': ['roadmap', 'kpi_kri'],
        'applicable_domains': ['digital_transformation'],
        'label_ar': 'هيئة الحكومة الرقمية',
        'label_en': 'DGA Digital Government',
    },
    {
        'framework_id': 'sama_csf',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'financial_cyber',
        'requirement_intent': 'Financial sector cyber resilience',
        'evidence_examples': ['SAMA CSF assessment'],
        'typical_owner': 'CRO',
        'mapped_output_sections': ['risk', 'roadmap'],
        'applicable_domains': ['cyber', 'enterprise_risk_management'],
        'label_ar': 'إطار ساما للأمن السيبراني',
        'label_en': 'SAMA Cybersecurity Framework',
    },
    {
        'framework_id': 'iso_27001',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'isms',
        'requirement_intent': 'Information security management system',
        'evidence_examples': ['SoA', 'Risk treatment plan'],
        'typical_owner': 'CISO',
        'mapped_output_sections': ['pillars', 'gap_analysis'],
        'applicable_domains': ['cyber', 'global_standards'],
        'label_ar': 'ISO 27001',
        'label_en': 'ISO/IEC 27001',
    },
    {
        'framework_id': 'iso_22301',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'business_continuity',
        'requirement_intent': 'Business continuity management',
        'evidence_examples': ['BCP tests', 'BIA'],
        'typical_owner': 'BCM Manager',
        'mapped_output_sections': ['roadmap', 'risk'],
        'applicable_domains': ['enterprise_risk_management', 'global_standards'],
        'label_ar': 'ISO 22301',
        'label_en': 'ISO 22301 BCM',
    },
    {
        'framework_id': 'nist_csf_2',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'identify_protect_detect',
        'requirement_intent': 'NIST CSF 2.0 functions coverage',
        'evidence_examples': ['CSF profile', 'Tier assessment'],
        'typical_owner': 'CISO',
        'mapped_output_sections': ['pillars', 'gap_analysis'],
        'applicable_domains': ['cyber', 'global_standards'],
        'label_ar': 'إطار NIST للأمن السيبراني 2.0',
        'label_en': 'NIST Cybersecurity Framework 2.0',
    },
    {
        'framework_id': 'nist_ai_rmf',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'ai_governance',
        'requirement_intent': 'AI risk management lifecycle',
        'evidence_examples': ['Model inventory', 'AI impact assessment'],
        'typical_owner': 'AI Governance Lead',
        'mapped_output_sections': ['vision_objectives', 'risk'],
        'applicable_domains': ['artificial_intelligence'],
        'label_ar': 'إطار NIST لإدارة مخاطر الذكاء الاصطناعي',
        'label_en': 'NIST AI RMF',
    },
    {
        'framework_id': 'iso_31000',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'enterprise_risk',
        'requirement_intent': 'Enterprise risk management principles',
        'evidence_examples': ['Risk appetite statement', 'ERM framework'],
        'typical_owner': 'CRO',
        'mapped_output_sections': ['vision_objectives', 'confidence_risk'],
        'applicable_domains': ['enterprise_risk_management'],
        'label_ar': 'ISO 31000',
        'label_en': 'ISO 31000 ERM',
    },
    {
        'framework_id': 'coso_erm',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'internal_control',
        'requirement_intent': 'COSO ERM components alignment',
        'evidence_examples': ['Control matrix', 'Board risk reporting'],
        'typical_owner': 'CRO',
        'mapped_output_sections': ['governance', 'kpi_kri'],
        'applicable_domains': ['enterprise_risk_management'],
        'label_ar': 'COSO لإدارة المخاطر',
        'label_en': 'COSO ERM',
    },
    {
        'framework_id': 'dama_dmbok',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'data_management',
        'requirement_intent': 'Data management capability areas',
        'evidence_examples': ['DG maturity assessment'],
        'typical_owner': 'CDO',
        'mapped_output_sections': ['pillars', 'roadmap'],
        'applicable_domains': ['data_management'],
        'label_ar': 'DAMA DMBOK',
        'label_en': 'DAMA DMBOK',
    },
    {
        'framework_id': 'eu_ai_act',
        'control_id': None,
        'coverage_granularity': 'capability_family',
        'capability_family': 'ai_regulatory',
        'requirement_intent': 'High-risk AI system obligations (reference)',
        'evidence_examples': ['Conformity assessment plan'],
        'typical_owner': 'Legal / AI Officer',
        'mapped_output_sections': ['policy', 'risk'],
        'applicable_domains': ['artificial_intelligence', 'global_standards'],
        'label_ar': 'قانون الاتحاد الأوروبي للذكاء الاصطناعي',
        'label_en': 'EU AI Act (reference)',
    },
]


def get_framework_entry(framework_id: str) -> Optional[Dict[str, Any]]:
    fid = (framework_id or '').strip().lower()
    for entry in FRAMEWORK_CATALOG:
        if entry.get('framework_id') == fid:
            return entry
    return None


def catalog_for_domain(domain_code: str) -> List[Dict[str, Any]]:
    code = (domain_code or '').strip().lower()
    aliases = {
        'cyber_security': 'cyber',
        'data_management': 'data_management',
        'data': 'data_management',
        'ai': 'artificial_intelligence',
        'artificial_intelligence': 'artificial_intelligence',
        'dt': 'digital_transformation',
        'digital_transformation': 'digital_transformation',
        'erm': 'enterprise_risk_management',
        'enterprise_risk_management': 'enterprise_risk_management',
        'global': 'global_standards',
        'global_standards': 'global_standards',
    }
    d = aliases.get(code, code)
    return [
        e for e in FRAMEWORK_CATALOG
        if d in (e.get('applicable_domains') or [])
    ]
