"""Platform-wide canonical registries for the Final Document Factory."""

from release_engine_v3.registries.platform_registries import (
    ARABIC_POLISH_REGISTRY,
    AUDIT_EVIDENCE_REGISTRY,
    CANONICAL_FAMILY_ALIASES,
    DOCUMENT_TYPE_SCHEMA_REGISTRY,
    DOMAIN_CAPABILITY_REGISTRY,
    ENGLISH_POLISH_REGISTRY,
    EXECUTIVE_RENDERING_REGISTRY,
    FRAMEWORK_TRACEABILITY_REGISTRY,
    GAP_REGISTRY,
    KPI_KRI_REGISTRY,
    POLICY_CONTROL_REGISTRY,
    PROCEDURE_STEP_REGISTRY,
    RISK_TREATMENT_REGISTRY,
    ROADMAP_REGISTRY,
    normalize_canonical_family,
    resolve_registries,
)

__all__ = [
    'ARABIC_POLISH_REGISTRY',
    'AUDIT_EVIDENCE_REGISTRY',
    'CANONICAL_FAMILY_ALIASES',
    'DOCUMENT_TYPE_SCHEMA_REGISTRY',
    'DOMAIN_CAPABILITY_REGISTRY',
    'ENGLISH_POLISH_REGISTRY',
    'EXECUTIVE_RENDERING_REGISTRY',
    'FRAMEWORK_TRACEABILITY_REGISTRY',
    'GAP_REGISTRY',
    'KPI_KRI_REGISTRY',
    'POLICY_CONTROL_REGISTRY',
    'PROCEDURE_STEP_REGISTRY',
    'RISK_TREATMENT_REGISTRY',
    'ROADMAP_REGISTRY',
    'normalize_canonical_family',
    'resolve_registries',
]
